baseURL = "https://s-show.github.io/"
title = "閑古鳥ブログ"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2021-{year} s-show. All Rights Reserved."
canonifyurls = true
publishDir = "docs"

# Multilingual mode
defaultContentLanguage = "jp"
defaultContentLanguageInSubdir = true # If you use only one language comment this option
#disableLanguages = ["fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

#[blackfriday]
#  hrefTargetBlank = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["json"]
  
[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/manifest+json"

[outputs]
  home = ["HTML", "RSS", "JSON", "MANIFEST"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = 'github'
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true