# Submenus are done this way: parent -> identifier
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"
#
[[main]]
  name = "自己紹介"
  url = "about/"
  weight = -107